modLoader="javafml"

loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = ""
logoFile = "icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.createknickknacks]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createknickknacks]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createknickknacks]]
modId="fusion"
type="required"
versionRange="${fusion_version_range}"
ordering="NONE"
side="CLIENT"

# [[dependencies.createknickknacks]]
# modId = "create"
# type="required"
# versionRange = "${create_version_range}"
# ordering = "NONE"
# side = "BOTH"

# [[dependencies."${mod_id}"]]
# modId = "flywheel"
# type = "required"
# versionRange = "${flywheel_version_range}"
# ordering = "AFTER"
# side = "CLIENT"

